### ISSUE TITLE
Nice work...

### ISSUE THREAD

**Issue by Kenner-G** [Pokemonjpups/ROBLOX-php#1]
How about a group payout function? 👍 

Melon#7877 if you'd like payment for it

**Comment by Pokemonjpups** [comment]
I don't really see the point in charging for something like that since it's pretty easy to make lol, but here https://github.com/Pokemonjpups/ROBLOX-php/blob/master/groups/payout.php

**Comment by Kenner-G** [comment]
Much love.

<3
